name: deploy-website
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-website.yml
      - apps/website/**
      - packages/**
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build
        run: docker build -t ${{ secrets.DOCKER_REGISTRY }}/mon/website:latest -f apps/website/Dockerfile .

      - name: setup tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: push
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/mon/website:latest

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-push
    concurrency:
      group: deploy
      cancel-in-progress: false
    steps:
      - name: setup tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: setup ssh
        run: |
          mkdir -p ~/.ssh
          echo '${{ secrets.SSH_PRIVATE_KEY }}' > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
      - name: deploy
        run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '${{ secrets.SSH_COMMAND }}'
