name: deploy-daemon
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-daemon.yml
      - apps/daemon/**
      - apps/packages/**
  workflow_dispatch:

concurrency:
  group: deploy-daemon
  cancel-in-progress: false

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build
        run: docker build -t ${{ secrets.DOCKER_REGISTRY }}/mon/daemon:latest -f apps/daemon/Dockerfile .

      - name: tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: push
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/mon/daemon:latest

      - name: setup ssh
        run: |
          mkdir -p ~/.ssh
          echo '${{ secrets.SSH_PRIVATE_KEY }}' > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
      - name: deploy
        run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '${{ secrets.SSH_COMMAND }}'
