name: test formatting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    environment: linting
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-bun@v2
      - run: bun i --frozen-lockfile
      - run: bun run format:check
