name: test linting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    environment: linting
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-bun@v4
      - run: bun i --frozen-lockfile
      - run: bun run lint
