name: test-docs
on:
  pull_request:
    paths:
      - .github/workflows/test-docs.yml
      - apps/docs/**
      - packages/**
  workflow_dispatch:

jobs:
  test-docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: build
        run: docker build -t docs -f apps/docs/Dockerfile .
